---
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip"

flake8:
  image: python:3.7
  before_script:
    - pip install flake8
  script:
    - flake8 kraken.py test_kraken.py
  cache:
    paths:
      - pip
